### ISSUE TITLE
Dropdown menu : Show on mouse click instead of hover (desktop layout)

### ISSUE THREAD

**Issue by vbaimas** [anace/keyboard-navigation#7]
Hello,

I really like this solution of accessible menu, but I see in action that in mobile layout the submenu click on hover and I really like it, but in desktop layout the submenu opens on hover instead of click. Over time I realized that this featured in navigation menu and especially in submenu, is not impove the accessibility and usability of user.

A lot of people and especially the designers believe that when their submenus open on hover, then they’re faster and easier to use and from one side they have right. The user save some milliseconds, and it might seem this way at first, but when you look deeper, you’ll notice that the opposite is true. Submenu that open on hover save users a click, but from the other side, that click is necessary for confirming that the user really wants to open a submenu.

Hover tunnels make it slower and harder for users to navigate. When a hover menu opens then the users can’t move their mouse to the menu item that they want in a straight line. If they do, their mouse will fall off the hover path and close the menu.

General I believe that the benefits of using click menus outweigh hover menus. As people who use some tools to create things around the web, need to know the harm they’re doing to users when their submenu opens on hover. The submenu should open when the user has made a really clear decision to open it and the clear decision is in the form of a click. In the last point, when a website behaves the way users want it to, then the tasks are quicker and easier to complete.

It's usually needed functionality to create multilevel clickable menu on desktop layout, so I was wondering is this something that we easily add as a feature in the accessible menu.

_(Sorry for the long message)_ 

Kind regards,
Vasilis

**Comment by anace** [comment]
Dear Vasilis, 

Thank you for your input. When I designed this menu, I was trying to strike a balance to satisfy the needs of various types of users. Some navigate with a mouse, others do the same with a keyboard, while others use assistive technologies.

For a mouse user's physical wellbeing, it is much better to hover than to click, as it is lighter on muscles and joints. Besides, mouse users also make a clear decision when they decide to hover a link.

Kindly,

Ana
